### ISSUE TITLE
Warning: Version constraints inside provider configuration blocks are deprecated

### ISSUE THREAD

**Issue by deloitteshellondemandlab** [metalstormbass/VulnerableAzure#3]
/home/runner/work/_temp/4f21fe9e-f531-4ed0-b69e-80c1f[7](https://github.com/deloitteshellondemandlab/VulnerableAzure/runs/6192422388?check_suite_focus=true#step:5:7)ab2355/terraform-bin plan
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/shellondemand/shellondemad/runs/run-uXcPmCsfQrcME69S

Waiting for the plan to start...

Terraform v1.1.9
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
╷
│ Warning: Version constraints inside provider configuration blocks are deprecated
│ 
│   on main-azure.tf line 2, in provider "azurerm":
│    2:     version = "=2.0.0"
│ 
│ Terraform 0.13 and earlier allowed provider version constraints inside the
│ provider configuration block, but that is now deprecated and will be
│ removed in a future version of Terraform. To silence this warning, move the
│ provider version constraint into the required_providers block.
╵
╷
│ Error: Unsupported attribute
│ 
│   on outputs.tf line 6, in output "k[8](https://github.com/deloitteshellondemandlab/VulnerableAzure/runs/6192422388?check_suite_focus=true#step:5:8)_service_url":
│    6:   value ="${kubernetes_service.vuln-k8-service.load_balancer_ingress}"
│ 
│ This object has no argument, nested block, or exported attribute named
│ "load_balancer_ingress".
╵

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.

Hi Im getting this error , Any help thank you

**Comment by metalstormbass** [comment]
Try now.
