### ISSUE TITLE
Deploy Action Error

### ISSUE THREAD

**Issue by faiz-kt** [metalstormbass/VulnerableAzure#4]
Showing below error when it is building. Can you please help?

Run terraform plan
/home/runner/work/_temp/55ecdcb3-c110-4258-91e4-ffb077ba6133/terraform-bin plan
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/shellondemand/shellondemad/runs/run-rK8hd69fF5fatEcZ

Waiting for the plan to start...

Terraform v1.1.9
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
╷
│ Warning: Version constraints inside provider configuration blocks are deprecated
│ 
│   on main-azure.tf line 2, in provider "azurerm":
│    2:     version = "=2.0.0"
│ 
│ Terraform 0.13 and earlier allowed provider version constraints inside the
│ provider configuration block, but that is now deprecated and will be
│ removed in a future version of Terraform. To silence this warning, move the
│ provider version constraint into the required_providers block.
╵
╷
│ Error: Unsupported argument
│ 
│   on aks.tf line 45, in provider "kubernetes":
│   45:     load_config_file = false
│ 
│ An argument named "load_config_file" is not expected here.
╵

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.

**Comment by metalstormbass** [comment]
Give it a shot now
